In [1]:
# Galaxy AI Adoption Risk Intelligence Platform
# Notebook 01: Data Understanding

import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
# Check files inside the data_raw folder

data_raw_path = Path("../data_raw")

print("Looking inside:", data_raw_path.resolve())

for file in data_raw_path.iterdir():
    print(file.name)

Looking inside: C:\Users\brigh\Downloads\Galaxy_AI_Adoption_Risk_Platform\data_raw
global_mobile_reviews.csv
samsung_mobile_sales.csv

In [3]:
# Load the raw datasets into pandas DataFrames

reviews_path = Path("../data_raw/global_mobile_reviews.csv")
sales_path = Path("../data_raw/samsung_mobile_sales.csv")

reviews_df = pd.read_csv(reviews_path)
sales_df = pd.read_csv(sales_path)

print("Reviews dataset loaded successfully.")
print("Reviews rows and columns:", reviews_df.shape)

print("Sales dataset loaded successfully.")
print("Sales rows and columns:", sales_df.shape)

Reviews dataset loaded successfully.
Reviews rows and columns: (50000, 10)
Sales dataset loaded successfully.
Sales rows and columns: (1000, 10)

In [4]:
# Preview the first 5 rows of the mobile reviews dataset

reviews_df.head()

,review_id,customer_name,age,brand,model,price_usd,price_local,currency,exchange_rate_to_usd,rating
0,1,Aryan Maharaj,45,Realme,Realme 12 Pro,337.31,₹27996.73,INR,83.00,2
1,2,Davi Miguel Sousa,18,Realme,Realme 12 Pro,307.78,R$1754.35,BRL,5.70,4
2,3,Pahal Balay,27,Google,Pixel 6,864.53,₹71755.99,INR,83.00,4
3,4,David Guzman,19,Xiaomi,Redmi Note 13,660.94,د.إ2425.65,AED,3.67,3
4,5,Yago Leão,38,Motorola,Edge 50,792.13,R$4515.14,BRL,5.70,3

In [5]:
# Preview the first 5 rows of the Samsung sales dataset

sales_df.head()

,Year,Quarter,Product Model,5G Capability,Units Sold,Revenue ($),Market Share (%),Regional 5G Coverage (%),5G Subscribers (millions),Avg 5G Speed (Mbps)
0,2019,Q1,Galaxy S10,No,26396,4.212951e+06,1.04,57.36,39.55,293.10
1,2019,Q1,Galaxy Note10,No,25671,7.240266e+06,2.82,85.80,42.58,67.46
2,2019,Q1,Galaxy S20,No,16573,2.560833e+07,-0.03,47.02,3.78,77.25
3,2019,Q1,Galaxy Note20,No,7177,2.198442e+07,0.84,25.70,23.41,105.27
4,2019,Q1,Galaxy S21,No,45633,1.634244e+07,2.36,89.13,44.43,206.17

In [6]:
# Show all column names in both datasets

print("Reviews dataset columns:")
print(reviews_df.columns)

print("\nSamsung sales dataset columns:")
print(sales_df.columns)

Reviews dataset columns:
Index(['review_id', 'customer_name', 'age', 'brand', 'model', 'price_usd',
       'price_local', 'currency', 'exchange_rate_to_usd', 'rating'],
      dtype='str')

Samsung sales dataset columns:
Index(['Year', 'Quarter', 'Product Model', '5G Capability', 'Units Sold',
       'Revenue ($)', 'Market Share (%)', 'Regional 5G Coverage (%)',
       '5G Subscribers (millions)', 'Avg 5G Speed (Mbps)'],
      dtype='str')

In [7]:
# Check basic information about the reviews dataset

reviews_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   review_id             50000 non-null  int64
 1   customer_name         50000 non-null  str
 2   age                   50000 non-null  int64
 3   brand                 50000 non-null  str
 4   model                 50000 non-null  str
 5   price_usd             50000 non-null  float64
 6   price_local           50000 non-null  str
 7   currency              50000 non-null  str
 8   exchange_rate_to_usd  50000 non-null  float64
 9   rating                50000 non-null  int64
dtypes: float64(2), int64(3), str(5)
memory usage: 3.8 MB

In [8]:
# Check basic information about the Samsung sales dataset

sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       1000 non-null   int64
 1   Quarter                    1000 non-null   str
 2   Product Model              1000 non-null   str
 3   5G Capability              1000 non-null   str
 4   Units Sold                 1000 non-null   int64
 5   Revenue ($)                1000 non-null   float64
 6   Market Share (%)           1000 non-null   float64
 7   Regional 5G Coverage (%)   1000 non-null   float64
 8   5G Subscribers (millions)  1000 non-null   float64
 9   Avg 5G Speed (Mbps)        1000 non-null   float64
dtypes: float64(5), int64(2), str(3)
memory usage: 78.3 KB

In [9]:
# Check the number of columns in the reviews dataset

print("Number of columns in reviews dataset:", reviews_df.shape[1])

print("\nColumn names:")
for column in reviews_df.columns:
    print(column)

Number of columns in reviews dataset: 10

Column names:
review_id
customer_name
age
brand
model
price_usd
price_local
currency
exchange_rate_to_usd
rating

In [10]:
# Load the raw datasets into pandas DataFrames

reviews_path = Path("../data_raw/global_mobile_reviews.csv")
sales_path = Path("../data_raw/samsung_mobile_sales.csv")

reviews_df = pd.read_csv(reviews_path)
sales_df = pd.read_csv(sales_path)

print("Reviews dataset loaded successfully.")
print("Reviews rows and columns:", reviews_df.shape)

print("Sales dataset loaded successfully.")
print("Sales rows and columns:", sales_df.shape)

Reviews dataset loaded successfully.
Reviews rows and columns: (50000, 25)
Sales dataset loaded successfully.
Sales rows and columns: (1000, 10)

In [11]:
# Check the number of columns in the reviews dataset

print("Number of rows and columns:", reviews_df.shape)

print("\nColumn names:")
for column in reviews_df.columns:
    print(column)

Number of rows and columns: (50000, 25)

Column names:
review_id
customer_name
age
brand
model
price_usd
price_local
currency
exchange_rate_to_usd
rating
review_text
sentiment
country
language
review_date
verified_purchase
battery_life_rating
camera_rating
performance_rating
design_rating
display_rating
review_length
word_count
helpful_votes
source

In [12]:
# Show the full structure of the updated reviews dataset

reviews_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   review_id             50000 non-null  int64
 1   customer_name         50000 non-null  str
 2   age                   50000 non-null  int64
 3   brand                 50000 non-null  str
 4   model                 50000 non-null  str
 5   price_usd             50000 non-null  float64
 6   price_local           50000 non-null  str
 7   currency              50000 non-null  str
 8   exchange_rate_to_usd  50000 non-null  float64
 9   rating                50000 non-null  int64
 10  review_text           50000 non-null  str
 11  sentiment             50000 non-null  str
 12  country               50000 non-null  str
 13  language              50000 non-null  str
 14  review_date           50000 non-null  str
 15  verified_purchase     50000 non-null  bool
 16  battery_life_rating   50000 non-null  int64
 17  camera_rating         50000 non-null  int64
 18  performance_rating    50000 non-null  int64
 19  design_rating         50000 non-null  int64
 20  display_rating        50000 non-null  int64
 21  review_length         50000 non-null  int64
 22  word_count            50000 non-null  int64
 23  helpful_votes         50000 non-null  int64
 24  source                50000 non-null  str
dtypes: bool(1), float64(2), int64(11), str(11)
memory usage: 9.2 MB

In [13]:
# Display all column names clearly

print("Reviews dataset columns:")

for column in reviews_df.columns:
    print("-", column)

Reviews dataset columns:
- review_id
- customer_name
- age
- brand
- model
- price_usd
- price_local
- currency
- exchange_rate_to_usd
- rating
- review_text
- sentiment
- country
- language
- review_date
- verified_purchase
- battery_life_rating
- camera_rating
- performance_rating
- design_rating
- display_rating
- review_length
- word_count
- helpful_votes
- source

In [14]:
# Preview the first 5 rows of the full reviews dataset

reviews_df.head()

,review_id,customer_name,age,brand,model,price_usd,price_local,currency,exchange_rate_to_usd,rating,review_text,sentiment,country,language,review_date,verified_purchase,battery_life_rating,camera_rating,performance_rating,design_rating,display_rating,review_length,word_count,helpful_votes,source
0,1,Aryan Maharaj,45,Realme,Realme 12 Pro,337.31,₹27996.73,INR,83.00,2,Not worth the money spent. Wouldn’t recommend.,Negative,India,Hindi,2023-11-06,True,1,1,3,2,1,46,7,1,Amazon
1,2,Davi Miguel Sousa,18,Realme,Realme 12 Pro,307.78,R$1754.35,BRL,5.70,4,Absolutely love this phone! The camera is next...,Positive,Brazil,Portuguese,2023-03-30,True,3,2,4,3,2,74,12,5,Flipkart
2,3,Pahal Balay,27,Google,Pixel 6,864.53,₹71755.99,INR,83.00,4,Loving the clean UI and fast updates. Loving i...,Positive,India,Hindi,2022-12-07,True,3,5,3,2,4,55,11,8,AliExpress
3,4,David Guzman,19,Xiaomi,Redmi Note 13,660.94,د.إ2425.65,AED,3.67,3,Build quality feels solid and durable. No regr...,Positive,UAE,English,2025-03-11,False,1,3,2,1,2,66,11,3,Amazon
4,5,Yago Leão,38,Motorola,Edge 50,792.13,R$4515.14,BRL,5.70,3,Not bad for daily use but could be optimized. ...,Neutral,Brazil,Portuguese,2023-09-29,True,3,3,2,2,1,73,12,0,BestBuy

In [15]:
# Check the number of reviews by brand

brand_counts = reviews_df["brand"].value_counts()

brand_counts

brand
Xiaomi      7241
Google      7234
Apple       7144
OnePlus     7136
Realme      7132
Motorola    7061
Samsung     7052
Name: count, dtype: int64

In [16]:
# Check how many Samsung reviews are in the dataset

samsung_reviews = reviews_df[reviews_df["brand"].str.lower() == "samsung"]

print("Number of Samsung reviews:", samsung_reviews.shape[0])
print("Number of columns:", samsung_reviews.shape[1])

samsung_reviews.head()

Number of Samsung reviews: 7052
Number of columns: 25

,review_id,customer_name,age,brand,model,price_usd,price_local,currency,exchange_rate_to_usd,rating,review_text,sentiment,country,language,review_date,verified_purchase,battery_life_rating,camera_rating,performance_rating,design_rating,display_rating,review_length,word_count,helpful_votes,source
14,15,Ms Hollie Phillips,39,Samsung,Galaxy Note 20,1146.49,£894.26,GBP,0.78,3,"Phone is fine, not the best in this range. Fin...",Neutral,UK,English,2025-09-17,True,2,3,1,2,3,68,14,4,BestBuy
29,30,Chaaya Saran,30,Samsung,Galaxy S24,1369.88,₹113700.04,INR,83.00,3,Fast charging is a lifesaver. Absolutely worth...,Positive,India,Hindi,2023-06-24,True,3,3,3,5,3,50,8,5,BestBuy
34,35,Paula Moreno,45,Samsung,Galaxy A55,1071.57,C$1478.77,CAD,1.38,4,Loving the clean UI and fast updates. Best pur...,Positive,Canada,English,2022-10-22,True,4,5,5,4,2,64,12,4,Flipkart
39,40,Vaishnavi Gandhi,38,Samsung,Galaxy S24,1147.47,₹95240.01,INR,83.00,2,Fast charging is a lifesaver. Absolutely worth...,Positive,India,Hindi,2023-12-07,True,1,2,2,1,2,50,8,4,eBay
42,43,Michael Brooks,29,Samsung,Galaxy S24,924.51,$924.51,USD,1.00,4,Display is crisp and vibrant — perfect for gam...,Positive,USA,English,2025-01-03,False,4,4,3,3,4,78,14,5,Flipkart

In [17]:
# Check sentiment distribution in the full reviews dataset

sentiment_counts = reviews_df["sentiment"].value_counts()

sentiment_counts

sentiment
Positive    27540
Neutral     12549
Negative     9911
Name: count, dtype: int64

In [18]:
# Check sentiment distribution for Samsung reviews only

samsung_sentiment_counts = samsung_reviews["sentiment"].value_counts()

samsung_sentiment_counts

sentiment
Positive    3872
Neutral     1778
Negative    1402
Name: count, dtype: int64

In [19]:
# Check rating distribution for all brands

reviews_df["rating"].value_counts().sort_index()

rating
1     6377
2     9803
3    12449
4    14029
5     7342
Name: count, dtype: int64

In [20]:
# Check rating distribution for Samsung reviews

samsung_reviews["rating"].value_counts().sort_index()

rating
1     878
2    1393
3    1861
4    1888
5    1032
Name: count, dtype: int64

# Defining the Prediction Target

In this project, the prediction target is customer dissatisfaction risk.

A review is considered high risk when the rating is low or the sentiment is negative. This helps us identify customers or product experiences that could reduce trust and future adoption of Galaxy AI devices.

In [21]:
# Create a dissatisfaction risk target variable

reviews_df["dissatisfaction_risk"] = reviews_df.apply(
    lambda row: 1 if (row["rating"] <= 2 or row["sentiment"] == "Negative") else 0,
    axis=1
)

# Check the distribution of the new target variable
risk_counts = reviews_df["dissatisfaction_risk"].value_counts()

risk_counts

dissatisfaction_risk
0    32764
1    17236
Name: count, dtype: int64

In [22]:
# Create readable labels for the dissatisfaction risk variable

reviews_df["risk_label"] = reviews_df["dissatisfaction_risk"].map({
    1: "High Dissatisfaction Risk",
    0: "Low Dissatisfaction Risk"
})

reviews_df[["brand", "model", "rating", "sentiment", "dissatisfaction_risk", "risk_label"]].head()

,brand,model,rating,sentiment,dissatisfaction_risk,risk_label
0,Realme,Realme 12 Pro,2,Negative,1,High Dissatisfaction Risk
1,Realme,Realme 12 Pro,4,Positive,0,Low Dissatisfaction Risk
2,Google,Pixel 6,4,Positive,0,Low Dissatisfaction Risk
3,Xiaomi,Redmi Note 13,3,Positive,0,Low Dissatisfaction Risk
4,Motorola,Edge 50,3,Neutral,0,Low Dissatisfaction Risk

In [23]:
# Update Samsung reviews after creating the risk column

samsung_reviews = reviews_df[reviews_df["brand"].str.lower() == "samsung"]

# Count Samsung dissatisfaction risk
samsung_risk_counts = samsung_reviews["risk_label"].value_counts()

samsung_risk_counts

risk_label
Low Dissatisfaction Risk     4627
High Dissatisfaction Risk    2425
Name: count, dtype: int64

In [24]:
# Calculate Samsung dissatisfaction risk percentage

samsung_risk_percentage = samsung_reviews["risk_label"].value_counts(normalize=True) * 100

samsung_risk_percentage.round(2)

risk_label
Low Dissatisfaction Risk     65.61
High Dissatisfaction Risk    34.39
Name: proportion, dtype: float64

# Understanding the Drivers of Samsung Dissatisfaction Risk

Now that we know a significant percentage of Samsung reviews show dissatisfaction risk, we need to identify which product features are most associated with that risk.

We compare feature ratings such as battery life, camera, performance, design, and display between high-risk and low-risk Samsung reviews.

In [25]:
# Compare Samsung feature ratings by dissatisfaction risk group

feature_columns = [
    "battery_life_rating",
    "camera_rating",
    "performance_rating",
    "design_rating",
    "display_rating"
]

samsung_feature_risk_summary = samsung_reviews.groupby("risk_label")[feature_columns].mean().round(2)

samsung_feature_risk_summary

,battery_life_rating,camera_rating,performance_rating,design_rating,display_rating
risk_label,,,,,
High Dissatisfaction Risk,1.56,1.55,1.56,1.56,1.56
Low Dissatisfaction Risk,3.32,3.30,3.30,3.30,3.29

In [26]:
# Compare average overall rating by risk group

samsung_rating_risk_summary = samsung_reviews.groupby("risk_label")["rating"].mean().round(2)

samsung_rating_risk_summary

risk_label
High Dissatisfaction Risk    1.71
Low Dissatisfaction Risk     3.85
Name: rating, dtype: float64

In [27]:
# Identify Samsung models with the highest number of high-risk reviews

samsung_high_risk = samsung_reviews[samsung_reviews["risk_label"] == "High Dissatisfaction Risk"]

high_risk_by_model = (
    samsung_high_risk["model"]
    .value_counts()
    .head(10)
)

high_risk_by_model

model
Galaxy A55        641
Galaxy S24        620
Galaxy Note 20    586
Galaxy Z Flip     578
Name: count, dtype: int64

In [28]:
# Identify countries with the highest number of high-risk Samsung reviews

high_risk_by_country = (
    samsung_high_risk["country"]
    .value_counts()
    .head(10)
)

high_risk_by_country

country
India        318
UK           315
Brazil       312
USA          308
Germany      302
Australia    294
UAE          291
Canada       285
Name: count, dtype: int64

In [29]:
# Calculate dissatisfaction risk percentage by Samsung model

model_risk_summary = (
    samsung_reviews
    .groupby("model")
    .agg(
        total_reviews=("review_id", "count"),
        high_risk_reviews=("dissatisfaction_risk", "sum"),
        average_rating=("rating", "mean"),
        average_battery_rating=("battery_life_rating", "mean"),
        average_camera_rating=("camera_rating", "mean"),
        average_performance_rating=("performance_rating", "mean"),
        average_design_rating=("design_rating", "mean"),
        average_display_rating=("display_rating", "mean")
    )
    .reset_index()
)

model_risk_summary["high_risk_percentage"] = (
    model_risk_summary["high_risk_reviews"] / model_risk_summary["total_reviews"] * 100
).round(2)

model_risk_summary = model_risk_summary.sort_values(
    by="high_risk_percentage",
    ascending=False
)

model_risk_summary.head(10)

,model,total_reviews,high_risk_reviews,average_rating,average_battery_rating,average_camera_rating,average_performance_rating,average_design_rating,average_display_rating,high_risk_percentage
0,Galaxy A55,1788,641,3.090604,2.721477,2.676174,2.661633,2.694072,2.651007,35.85
2,Galaxy S24,1761,620,3.074957,2.678024,2.663827,2.650199,2.676320,2.670642,35.21
3,Galaxy Z Flip,1714,578,3.136523,2.725788,2.739207,2.750292,2.693116,2.742124,33.72
1,Galaxy Note 20,1789,586,3.153717,2.740637,2.729458,2.756847,2.747345,2.725545,32.76

In [30]:
# Environment: VS Code Jupyter Notebook
# Create a feature gap analysis table

feature_gap_summary = samsung_feature_risk_summary.T.reset_index()

feature_gap_summary = feature_gap_summary.rename(columns={
    "index": "feature"
})

feature_gap_summary["risk_gap"] = (
    feature_gap_summary["Low Dissatisfaction Risk"] -
    feature_gap_summary["High Dissatisfaction Risk"]
).round(2)

feature_gap_summary = feature_gap_summary.sort_values(
    by="risk_gap",
    ascending=False
)

feature_gap_summary

risk_label,feature,High Dissatisfaction Risk,Low Dissatisfaction Risk,risk_gap
0,battery_life_rating,1.56,3.32,1.76
1,camera_rating,1.55,3.30,1.75
2,performance_rating,1.56,3.30,1.74
3,design_rating,1.56,3.30,1.74
4,display_rating,1.56,3.29,1.73

In [31]:
# Environment: VS Code Jupyter Notebook
# Calculate dissatisfaction risk percentage by country for Samsung reviews

country_risk_summary = (
    samsung_reviews
    .groupby("country")
    .agg(
        total_reviews=("review_id", "count"),
        high_risk_reviews=("dissatisfaction_risk", "sum"),
        average_rating=("rating", "mean")
    )
    .reset_index()
)

country_risk_summary["high_risk_percentage"] = (
    country_risk_summary["high_risk_reviews"] / country_risk_summary["total_reviews"] * 100
).round(2)

country_risk_summary = country_risk_summary.sort_values(
    by="high_risk_percentage",
    ascending=False
)

country_risk_summary

,country,total_reviews,high_risk_reviews,average_rating,high_risk_percentage
6,UK,877,315,3.055872,35.92
4,India,891,318,3.098765,35.69
0,Australia,852,294,3.167840,34.51
7,USA,896,308,3.099330,34.38
1,Brazil,916,312,3.129913,34.06
3,Germany,888,302,3.115991,34.01
5,UAE,864,291,3.125000,33.68
2,Canada,868,285,3.119816,32.83

In [32]:
# Environment: VS Code Jupyter Notebook
# Create business recommendations based on feature risk gaps

recommendation_map = {
    "battery_life_rating": "Improve battery optimization for AI features and communicate battery performance more clearly.",
    "camera_rating": "Strengthen camera experience messaging, especially for content creation and AI-enhanced photography.",
    "performance_rating": "Improve performance stability, speed, and AI processing experience across Galaxy devices.",
    "design_rating": "Protect premium design perception and improve comfort/usability for future AI devices.",
    "display_rating": "Improve display quality communication and maintain strong screen experience as a Galaxy advantage."
}

feature_gap_summary["business_recommendation"] = feature_gap_summary["feature"].map(recommendation_map)

feature_gap_summary

risk_label,feature,High Dissatisfaction Risk,Low Dissatisfaction Risk,risk_gap,business_recommendation
0,battery_life_rating,1.56,3.32,1.76,Improve battery optimization for AI features a...
1,camera_rating,1.55,3.30,1.75,"Strengthen camera experience messaging, especi..."
2,performance_rating,1.56,3.30,1.74,"Improve performance stability, speed, and AI p..."
3,design_rating,1.56,3.30,1.74,Protect premium design perception and improve ...
4,display_rating,1.56,3.29,1.73,Improve display quality communication and main...

In [33]:
# Environment: VS Code Jupyter Notebook
# Save Samsung insight tables for later Power BI and reporting

output_folder = Path("../data_cleaned")
output_folder.mkdir(exist_ok=True)

samsung_reviews.to_csv(output_folder / "samsung_reviews_with_risk.csv", index=False)
feature_gap_summary.to_csv(output_folder / "samsung_feature_gap_summary.csv", index=False)
model_risk_summary.to_csv(output_folder / "samsung_model_risk_summary.csv", index=False)
country_risk_summary.to_csv(output_folder / "samsung_country_risk_summary.csv", index=False)

print("Samsung insight tables saved successfully.")

Samsung insight tables saved successfully.

# Preparing the Dataset for Prediction Modelling

The goal of the prediction model is to estimate whether a Samsung review shows high dissatisfaction risk.

To avoid data leakage, we will not use `rating` or `sentiment` as model input features because they were used to create the target variable.

In [34]:
# Environment: VS Code Jupyter Notebook
# Prepare the Samsung dataset for prediction modelling

model_columns = [
    "age",
    "price_usd",
    "verified_purchase",
    "battery_life_rating",
    "camera_rating",
    "performance_rating",
    "design_rating",
    "display_rating",
    "review_length",
    "word_count",
    "helpful_votes",
    "country",
    "language",
    "source",
    "model",
    "dissatisfaction_risk"
]

samsung_modeling_df = samsung_reviews[model_columns].copy()

samsung_modeling_df.head()

,age,price_usd,verified_purchase,battery_life_rating,camera_rating,performance_rating,design_rating,display_rating,review_length,word_count,helpful_votes,country,language,source,model,dissatisfaction_risk
14,39,1146.49,True,2,3,1,2,3,68,14,4,UK,English,BestBuy,Galaxy Note 20,0
29,30,1369.88,True,3,3,3,5,3,50,8,5,India,Hindi,BestBuy,Galaxy S24,0
34,45,1071.57,True,4,5,5,4,2,64,12,4,Canada,English,Flipkart,Galaxy A55,0
39,38,1147.47,True,1,2,2,1,2,50,8,4,India,Hindi,eBay,Galaxy S24,1
42,29,924.51,False,4,4,3,3,4,78,14,5,USA,English,Flipkart,Galaxy S24,0

In [35]:
# Environment: VS Code Jupyter Notebook
# Check missing values in the modelling dataset

missing_values = samsung_modeling_df.isnull().sum()

missing_values

age                     0
price_usd               0
verified_purchase       0
battery_life_rating     0
camera_rating           0
performance_rating      0
design_rating           0
display_rating          0
review_length           0
word_count              0
helpful_votes           0
country                 0
language                0
source                  0
model                   0
dissatisfaction_risk    0
dtype: int64

In [36]:
# Environment: VS Code Jupyter Notebook
# Check the data types of the modelling dataset

samsung_modeling_df.info()

<class 'pandas.DataFrame'>
Index: 7052 entries, 14 to 49996
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   7052 non-null   int64
 1   price_usd             7052 non-null   float64
 2   verified_purchase     7052 non-null   bool
 3   battery_life_rating   7052 non-null   int64
 4   camera_rating         7052 non-null   int64
 5   performance_rating    7052 non-null   int64
 6   design_rating         7052 non-null   int64
 7   display_rating        7052 non-null   int64
 8   review_length         7052 non-null   int64
 9   word_count            7052 non-null   int64
 10  helpful_votes         7052 non-null   int64
 11  country               7052 non-null   str
 12  language              7052 non-null   str
 13  source                7052 non-null   str
 14  model                 7052 non-null   str
 15  dissatisfaction_risk  7052 non-null   int64
dtypes: bool(1), float64(1), int64(10), str(4)
memory usage: 888.4 KB

In [37]:
# Environment: VS Code Jupyter Notebook
# Save the Samsung modelling dataset

samsung_modeling_df.to_csv(output_folder / "samsung_modeling_dataset.csv", index=False)

print("Samsung modelling dataset saved successfully.")

Samsung modelling dataset saved successfully.